//config
export const INIT_SYSTEM_CONFIG_DATA = "INIT_SYSTEM_CONFIG_DATA";
export const SET_SYSTEM_CONFIG_DATA = "SET_SYSTEM_CONFIG_DATA";

//弹出层
export const INIT_POPS_POPS_DATA = "INIT_POPS_POPS_DATA";

//初始化菜单
export const INIT_SYSTEM_MENUS_DATA = "INIT_SYSTEM_MENUS_DATA";

//路由列表
export const INIT_HOME_COMMON_TOP_ROUTE_DATA = "INIT_HOME_COMMON_TOP_ROUTE_DATA";

//会员折线图数据
export const INIT_HOME_DASHBOARD_TOP_LIST_DATA = "INIT_HOME_DASHBOARD_TOP_LIST_DATA";
export const INIT_HOME__DASHBOARD_LINE_DATA = "INIT_HOME__DASHBOARD_LINE_DATA";
export const INIT_HOME_DASHBOARD_AREA_DATA = "INIT_HOME_DASHBOARD_AREA_DATA";
export const INIT_HOME_DASHBOARD_BAR_DATA = "INIT_HOME_DASHBOARD_BAR_DATA";

//后台配置
export const INIT_TEST_TABS_DATA = "INIT_TEST_TABS_DATA";

//users
export const INIT_USER_STRUCT_DATA = "INIT_USER_STRUCT_DATA";
export const SET_USER_STRUCT_DATA = "SET_USER_STRUCT_DATA";

//userlist
export const SET_USER_LIST_DATA = "SET_USER_LIST_DATA";
export const INIT_USER_TREE_OPTIONS_DATA = "INIT_USER_TREE_OPTIONS_DATA";

